# Generated by Django 4.2.7 on 2023-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentdataset",
            name="average_year_of_construction",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="saledataentry",
            name="year_of_construction",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="saledataset",
            name="average_year_of_construction",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
