# Generated by Django 4.2.7 on 2023-11-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_rentdataset_average_year_of_construction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentdataentry",
            name="number_of_apartment_floors",
        ),
        migrations.RemoveField(
            model_name="saledataentry",
            name="number_of_apartment_floors",
        ),
    ]
