# Generated by Django 4.2.7 on 2023-11-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_rentdataentry_number_of_apartment_floors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentdataentry",
            name="number_of_rooms",
        ),
        migrations.RemoveField(
            model_name="saledataentry",
            name="number_of_rooms",
        ),
    ]
